" When started as "evim", evim.vim will already have done these settings.
if v:progname =~? "evim"
	finish
endif

let mapleader = ","

" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible
filetype off

set runtimepath^=~/.vim  "Use instead of "vimfiles" on windows

call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-markdown'

Plug 'kana/vim-altr'
Plug 'mustache/vim-mustache-handlebars'
Plug 'davidhalter/jedi-vim'

Plug 'pangloss/vim-javascript'

" Themes
Plug 'flazz/vim-colorschemes'
Plug 'chriskempson/base16-vim'

Plug 'cakebaker/scss-syntax.vim'

Plug 'rking/ag.vim'
let g:agprg="ag --nocolor --nogroup --column"
nnoremap <leader>f :Ag! "<C-R><C-W>"

" Airline
Plug 'bling/vim-airline'

Plug 'scrooloose/syntastic'

Plug 'scrooloose/nerdtree'
nnoremap <leader>x :NERDTreeToggle<CR>

Plug 'kien/ctrlp.vim'

Plug 'sjl/splice.vim'

if has("python")
	Plug 'OmniSharp/omnisharp-vim'
	let g:syntastic_cs_checkers = ['syntax', 'semantic', 'issues']
	set completeopt=longest,menuone,preview
	set noshowmatch
	let g:OmniSharp_timeout = 1
endif

Plug 'jmcantrell/vim-virtualenv'
if filereadable($HOME . "/.vim-site-plugins.vimrc")
	source ~/.vim-site-plugins.vimrc
endif

call plug#end()

filetype plugin indent on

set nowrap

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

if has("vms")
	set nobackup		" do not keep a backup file, use versions instead
else
	set backup		" keep a backup file
endif

set backupdir=~/vimtmp,.
set directory=~/vimtmp,.

" Tab and editor settings
set history=50		" keep 50 lines of command line history
set showcmd		" display incomplete commands
set shiftwidth=8
set tabstop=8
set laststatus=2
set wildmenu           " Turn on WiLd menu
set hidden             " Change buffer - without saving
set encoding=utf-8

" Searching
set incsearch		" do incremental searching
set ignorecase
set smartcase
set wildignore+=*.o,*.obj,*.exe,*.so,*.dll,*.pyc,.svn,.hg,.bzr,.git

" Visual stuff
set showmatch " Show matching brackets
set number " always show linenumbers
set ruler " show the cursor position all the time

" For Win32 GUI: remove 't' flag from 'guioptions': no tearoff menu entries
" let &guioptions = substitute(&guioptions, "t", "", "g")

" Don't use Ex mode, use Q for formatting
map Q gq

" Use ESC to turn off highlighting
nnoremap <leader>q :noh<CR>

" Use space to get into command mode
nnoremap <Space> :

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

nmap <leader>o <Plug>(altr-forward)
nmap <leader>p <Plug>(altr-back)

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
	set mouse=a
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
	syntax on
	set hlsearch

	set background=dark
	let base16colorspace=256  " Access colors present in 256 colorspace
	colorscheme base16-default-dark
endif

set guifont=terminus\ 9,bitstream\ vera\ sans\ mono:h8,consolas:h9

set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=l
set guioptions-=b
set guioptions-=L
set guioptions-=e

inoremap  <Up>     <NOP>
inoremap  <Down>   <NOP>
inoremap  <Left>   <NOP>
inoremap  <Right>  <NOP>
noremap   <Up>     <NOP>
noremap   <Down>   <NOP>
noremap   <Left>   <NOP>
noremap   <Right>  <NOP>

" ---------------
" Sounds
" ---------------
set noerrorbells
set novisualbell
set t_vb=

" ---------------
" Mouse
" ---------------
set mousehide  " Hide mouse after chars typed

highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS

" Only do this part when compiled with support for autocommands.
if has("autocmd")

	" Put these in an autocmd group, so that we can delete them easily.
	augroup vimrcEx
		au!

		" For all text files set 'textwidth' to 78 characters.
		autocmd FileType text setlocal textwidth=80

		" When editing a file, always jump to the last known cursor position.
		" Don't do it when the position is invalid or when inside an event handler
		" (happens when dropping a file on gvim).
		" Also don't do it when the mark is in the first line, that is the default
		" position when opening a file.
		autocmd BufReadPost *
					\ if line("'\"") > 1 && line("'\"") <= line("$") |
					\   exe "normal! g`\"" |
					\ endif

	augroup END

	" Show trailing whitepace and spaces before a tab:
	autocmd Syntax * syn match ExtraWhitespace /\s\+$\| \+\ze\t/ containedin=ALL

	augroup omnisharp_commands
		autocmd!

		" use correct complete func
		autocmd FileType cs setlocal omnifunc=OmniSharp#Complete

		" automatic syntax check on save
		autocmd BufEnter,TextChanged,InsertLeave *.cs SyntasticCheck

		" display type info on idle
		autocmd CursorHold *.cs call OmniSharp#TypeLookupWithoutDocumentation()

		" hotkeys
		autocmd FileType cs nnoremap <leader>gd :OmniSharpGotoDefinition<cr>
		autocmd FileType cs nnoremap <leader>fi :OmniSharpFindImplementations<cr>
		autocmd FileType cs nnoremap <leader>ft :OmniSharpFindType<cr>
		autocmd FileType cs nnoremap <leader>fs :OmniSharpFindSymbol<cr>
		autocmd FileType cs nnoremap <leader>fu :OmniSharpFindUsages<cr>

		" find members in current buffer
		autocmd FileType cs nnoremap <leader>fm :OmniSharpFindMembers<cr>

		" fix issues (cursor on line)
		autocmd FileType cs nnoremap <leader>x :OmniSharpFixIssue<cr>
		autocmd FileType cs nnoremap <leader>fx :OmniSharpFixUsings<cr>
		autocmd FileType cs nnoremap <leader>tt :OmniSharpTypeLookup<cr>
		autocmd FileType cs nnoremap <leader>dc :OmniSharpDocumentation<cr>

		autocmd FileType cs nnoremap <C-K> :OmniSharpNavigateUp<cr>
		autocmd FileType cs nnoremap <C-J> :OmniSharpNavigateDown<cr>

		autocmd FileType cs set updatetime=1000

	augroup END
else

	set autoindent		" always set autoindenting on

endif " has("autocmd")

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
	command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
				\ | wincmd p | diffthis
endif
