#! /bin/sh

bspc desktop ^1 -n I
bspc monitor -a II III IV V VI VII VIII IX X

bspc rule -a Gimp -d ^8 --follow --floating
bspc rule -a Chromium -d ^2
bspc rule -a mplayer2 --floating
bspc rule -a Kupfer.py --focus
bspc rule -a Screenkey --unmanage

bspc config border_width        2
bspc config window_gap          12
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# monitor padding for panel
xrandr --output LVDS-0 --primary
bspc config -m primary top_padding 18

# default cursor
xsetroot -cursor_name left_ptr

# background
feh --bg-scale pics/walls/invisible.png

# panel
panel &
